# Generated by Django 4.0.3 on 2022-03-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_newuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='first_name',
        ),
    ]
