# Generated by Django 4.0.3 on 2022-03-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_newuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.CharField(choices=[('teachers', 'Teacher'), ('students', 'Student'), ('admin', 'Admin')], default='student', max_length=150),
        ),
    ]
