# Generated by Django 4.0.3 on 2022-03-03 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_newuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newuser',
            name='date_of_birth',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('transgender', 'transgender')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='standard',
            field=models.IntegerField(default=0),
        ),
    ]
